/**
 * Build-time script: generates src/generated/proto-root.ts from the .proto file.
 * Run with: deno run -A scripts/gen-proto.ts
 */
import protobufjs from "npm:protobufjs@7.6.5";
import { writeFileSync, mkdirSync } from "node:fs";
import { resolve, dirname } from "node:path";

const __dirname = dirname(new URL(import.meta.url).pathname);
const PROTO_PATH = resolve(__dirname, "..", "proto", "tfplugin6.proto");
const OUT_PATH = resolve(__dirname, "..", "src", "generated", "proto-root.ts");

const root = new protobufjs.Root();
root.loadSync(PROTO_PATH, { includeDirs: [resolve(__dirname, "..", "proto")] });

const json = root.toJSON();
const jsonStr = JSON.stringify(json);

mkdirSync(dirname(OUT_PATH), { recursive: true });

const code = `// AUTO-GENERATED by scripts/gen-proto.ts — DO NOT EDIT
export const PROTO_ROOT_JSON = ${JSON.stringify(jsonStr)} as const;
`;

writeFileSync(OUT_PATH, code);
console.log(`Generated ${OUT_PATH}`);
